<a href="https://colab.research.google.com/github/ajaymaliya597/REGex_Software/blob/main/dummy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
#Q1
arr = np.arange(1,11)
print(arr.shape)
print(arr.size)
print(arr.ndim)


(10,)
10
1


In [4]:
#Q2
arr = np.arange(1,10)
print(np.zeros((3,3)))
print(np.ones((2,4)))
print(np.eye((4)))
print()
print()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]




In [5]:
#Q3

print(np.arange(1,21))
print(np.linspace(1,20,5))
print()
print()
print()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1.    5.75 10.5  15.25 20.  ]





In [6]:
#Q4
arr = np.arange(1,5)
print(arr.dtype)
print(arr.astype(float))
print()
print()
print()

int64
[1. 2. 3. 4.]





In [7]:
#Q5
arr = np.arange(10,60,10)
print(arr[0])
print(arr[-1:])
print(arr[len(arr)//2])
print(arr[::-1])
print()

10
[50]
30
[50 40 30 20 10]



In [8]:
#Q6
arr = np.array([10,20,30,40,50])
print(arr[0:3])
print(arr[-2:])
print(arr[1:5])
print(arr[1::2])
print()

[10 20 30]
[40 50]
[20 30 40 50]
[20 40]



In [9]:
#Q7
arr = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])
print(arr[1,1])
print(arr[1,0:])
print(arr[0:,2])
print(arr[2:3,0:])
print()

5
[4 5 6]
[3 6 9]
[[7 8 9]]



In [10]:
#Q8
arr = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])
print(arr[0:2,0:2])
print(arr[1:3,1:3])
print(arr[0::2,0::2])
print()
print()

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]
[[1 3]
 [7 9]]




In [11]:
#Q9
arr = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])
print(arr[::-1,0:])
print(arr[0:,::-1])
print(arr[::-1,::-1])
print()
print()

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]




In [12]:
#Q10
arr = np.array([5,10,15,20,25,30])
print(arr[arr > 15])
print(arr[arr%2==0])
arr[arr > 20] = 0
print(arr)
print()
print()

[20 25 30]
[10 20 30]
[ 5 10 15 20  0  0]




In [13]:
#Q11
arr = np.array([
[10,20,30],
[40,50,60]
])
print(arr[25<arr])
arr[25<arr]=-1
print(arr)

[30 40 50 60]
[[10 20 -1]
 [-1 -1 -1]]


In [14]:
#Q12
arr = np.array([1,2,3,4])
print(arr + 10)

[11 12 13 14]


In [15]:
#Q13
A = np.array([
[10,20,30],
[40,50,60]
])
B = np.array([1,2,3])
print(B + A)

[[11 22 33]
 [41 52 63]]


In [16]:
#Q14

A = np.array([
[10,20,30],
[40,50,60]
])
B = np.array([
[1],
[2]
])
print(B + A)

[[11 21 31]
 [42 52 62]]


In [17]:
#Q15
A = np.array([
[10,20,30],
[40,50,60],
[70,80,90],
[100,110,120]
])
print("(2,3) + (3,)  -> INVALID")
print("(3,2) + (2,)  -> INVALID")
print("(2,3) + (2,)  -> INVALID")

(2,3) + (3,)  -> INVALID
(3,2) + (2,)  -> INVALID
(2,3) + (2,)  -> INVALID


In [18]:
#Q16
arr = np.array([
[1,2,3],
[4,5,6]
])
print(arr.sum())
print(arr[0:,:].sum(axis=0))
print(arr[:,0:].sum(axis=1))
print()
print()

21
[5 7 9]
[ 6 15]




In [19]:
#Q17
arr = np.array([
[1,2,3],
[4,5,6]
])
print(np.mean(arr,axis=1))
print(np.mean(arr,axis=0))
print(np.max(arr,axis=1))
print(np.min(arr,axis=0))
print()

[2. 5.]
[2.5 3.5 4.5]
[3 6]
[1 2 3]



In [20]:
#Q18
arr = np.array([10,20,30,40,50])
print("standard deviation: ",np.std(arr))
print()
print()
print()
print()

standard deviation:  14.142135623730951






In [21]:
#Q19
arr = np.array([1,2,3,4,5,6])

print(arr.reshape(2,3))
print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [22]:
#20

arr = np.array([1,2,3,4,5,6])
f = arr.flatten
r = arr.ravel
print(f)
print(r) #return views

<built-in method flatten of numpy.ndarray object at 0x7c3ba7015ef0>
<built-in method ravel of numpy.ndarray object at 0x7c3ba7015ef0>


In [23]:
#Q21
a = np.array([1,2,3])
b = a

b[0] = 100
print(b)

[100   2   3]


In [24]:
#Q22
a = np.array([1,2,3])

b = a.copy()

b[0] = 100

print("a :", a)
print("b :", b)

a : [1 2 3]
b : [100   2   3]


In [25]:
#Q23
arr = np.array([10,20,30,40,50])

normalized = (arr - arr.min()) / (arr.max() - arr.min())

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [26]:
#Q24
arr = np.array([10,20,30,40,50])

normalized = (arr - arr.min()) / (arr.max() - arr.min())

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [27]:
#Q25
arr = np.array([
[10,100],
[20,200],
[30,300]
])
normalized = (arr-arr.min())/(arr.max()-arr.min())

print(normalized)
print()
print()
print()
print()

[[0.         0.31034483]
 [0.03448276 0.65517241]
 [0.06896552 1.        ]]






In [28]:
#Q26
arr = np.array([
[10,100],
[20,200],
[30,300]
])
normalized = (arr-arr.min())/(arr.max()-arr.min())

print(normalized)
print()
print()
print()
print()

[[0.         0.31034483]
 [0.03448276 0.65517241]
 [0.06896552 1.        ]]






In [56]:
#Q27
arr = np.random.randint(1,10,5)
print(arr)
arr1 = np.random.randint(50,101,9).reshape(3,3)
print(arr1)
arr1 = np.random.randint(50,101,(3,3)).reshape(3,3)
print(arr1)

[9 9 2 8 3]
[[89 70 91]
 [99 71 68]
 [87 72 90]]
[[77 87 73]
 [85 99 79]
 [72 91 59]]


In [58]:
#Q28
arr = [10,20,30,40,50]
a = np.random.choice(arr)
print(a)
a = np.random.choice(arr,3)
print(a)
print()
print()
print()

40
[40 40 50]





In [60]:
#Q29
arr = np.random.normal(size=5)
print(arr)
arr = np.random.randn(2,3)
print(arr)
print()
print()
print()
print()

[ 0.42383635 -0.6981503   0.48402527 -2.49106355  0.07955019]
[[ 1.47567863 -1.71067337 -1.25506101]
 [-0.5034154  -0.93651935 -1.13053587]]






In [94]:


print(np.random.randint(1,100,3))

np.random.seed(10)

print(np.random.randint(1,100,3))

[29 90 94]
[10 16 65]


In [89]:
#Q31
arr = np.arange(1,11)
print()
print()
print()
print()
print()

In [32]:
#Q31
arr = np.arange(1,11)
print()
print()
print()
print()
print()

In [105]:
#Q32
arr = np.array([1,2,3,4,5])
print(np.random.permutation(arr))
print(np.random.shuffle(arr))

[4 5 3 1 2]
None


In [112]:
#Q33
arr = np.random.randint(1,51,(4,4))
print(arr.max())
print(arr.min())
print(arr.sum(axis=1))
print(arr.mean(axis=0))
print(arr)

45
5
[ 97  93 127  54]
[27.25 15.75 34.25 15.5 ]
[[33 25 45  6]
 [ 5  8 25 25]
 [45 35 41 16]
 [14 25 16  7]]


In [115]:
#Q34
arr = np.random.randint(1,101,10)
print(arr)
print(arr[arr%2==0])
print(arr[arr>50])
arr[arr<30]=0
print(arr)
print()

[49 18 33 82 81 42 91 13 31 82]
[18 82 42 82]
[82 81 91 82]
[49  0 33 82 81 42 91  0 31 82]



In [129]:
#Q35
arr = np.random.randint(1,1001,8)
print(arr)
normalized = (arr - arr.min())/(arr.max() - arr.min())
print(normalized)
print()
print()
print()

[772 522 181 973 709 159 455 377]
[0.75307125 0.44594595 0.02702703 1.         0.67567568 0.
 0.36363636 0.26781327]





In [146]:
arr = np.arange(1,26).reshape(5,5)

print(arr)

print("Diagonal :", np.diag(arr))

np.fill_diagonal(arr,0)

print("After Replace:\n", arr)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal : [ 1  7 13 19 25]
After Replace:
 [[ 0  2  3  4  5]
 [ 6  0  8  9 10]
 [11 12  0 14 15]
 [16 17 18  0 20]
 [21 22 23 24  0]]


In [152]:
#Q37
arr = np.arange(1,4).reshape(3,1)
print(np.repeat(arr,3,axis=1))

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [159]:
#Q38
arr = np.random.randint(1,11,(3,3))
print(arr[::-1,0:])
print(arr[0:,::-1])
print(arr.flatten())
print()
print()

[[ 5  9 10]
 [ 6 10  3]
 [ 7  8 10]]
[[10  8  7]
 [ 3 10  6]
 [10  9  5]]
[ 7  8 10  6 10  3  5  9 10]




In [182]:
#Q39
arr = np.random.randint(1,10,(8,8))
print(arr[0,:])
print(arr[:,-1])
print(arr[3,3])
print(arr[np.ix_([0,-1],[0,-1])])
print()

[3 4 1 1 6 9 7 7]
[7 8 1 8 7 4 8 1]
9
[[3 7]
 [1 1]]

