<a href="https://colab.research.google.com/github/ajaymaliya597/REGex_Software/blob/main/dummy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
#Q1
arr = np.arange(1,11)
print(arr.shape)
print(arr.size)
print(arr.ndim)


(10,)
10
1


In [17]:
#Q2
arr = np.arange(1,10)
print(np.zeros((3,3)))
print(np.ones((2,4)))
print(np.eye((2,4)))
print()
print()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]






In [ ]:
#Q1
arr = np.arange(1,11)
print()
print()
print()
print()
print()

(10,)

In [ ]:
#Q1
arr = np.arange(1,11)
print()
print()
print()
print()
print()

(10,)

In [ ]:
#Q1
arr = np.arange(1,11)
print()
print()
print()
print()
print()

(10,)

In [ ]:
#Q1
arr = np.arange(1,11)
print()
print()
print()
print()
print()

(10,)

In [ ]:
#Q1
arr = np.arange(1,11)
print()
print()
print()
print()
print()

(10,)

In [ ]:
#Q1
arr = np.arange(1,11)
print()
print()
print()
print()
print()

(10,)

In [ ]:
#Q1
arr = np.arange(1,11)
print()
print()
print()
print()
print()

(10,)

In [ ]:
#Q1
arr = np.arange(1,11)
print()
print()
print()
print()
print()

(10,)

In [ ]:
#Q1
arr = np.arange(1,11)
print()
print()
print()
print()
print()

(10,)

In [ ]:
#Q1
arr = np.arange(1,11)
print()
print()
print()
print()
print()

(10,)

In [ ]:
#Q1
arr = np.arange(1,11)
print()
print()
print()
print()
print()

(10,)

In [ ]:
#Q1
arr = np.arange(1,11)
print()
print()
print()
print()
print()

(10,)