<a href="https://colab.research.google.com/github/ajaymaliya597/REGex_Software/blob/main/numpy_practice_assignment%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
#Q1
a = np.array([10,20, 30, 40, 50])
print(a)
print(a[-1])
print(a[1:4])
print(a[::-1])


[10 20 30 40 50]
50
[20 30 40]
[50 40 30 20 10]


In [4]:
#Q2
a = np.arange(1,7).reshape(2,3)
print("",a)
print("shape : ",a.shape)
print("2nd row :",a[1])
print(a[:,0].reshape(-1,1))


 [[1 2 3]
 [4 5 6]]
shape :  (2, 3)
2nd row : [4 5 6]
[[1]
 [4]]


In [5]:
# Q3
arr = np.array([1,2,3,4,5,6])
print(arr[1:5])
print(arr[:3])
print(arr[-3:])
print(arr[::-1])

[2 3 4 5]
[1 2 3]
[4 5 6]
[6 5 4 3 2 1]


In [6]:
# Q4
arr = np.array([1,2,3,4,5,6])
print(arr[::2])
print(arr[::-2])
print(arr[1::2])

[1 3 5]
[6 4 2]
[2 4 6]


In [12]:
# Q5
arr = np.array([
[10,20,30],
[40,50,60],
[70,80,90]
])
print('First two rows and first two columns: \n',arr[:2,:2])
print('last two rows and last two columns: \n',arr[-2:,-2:])
print(arr[1,:])
print(arr[:,2])
print(arr)

First two rows and first two columns: 
 [[10 20]
 [40 50]]
last two rows and last two columns: 
 [[50 60]
 [80 90]]
[40 50 60]
[30 60 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [14]:
# Q6
print(arr[:2,1:])
print(arr[::2,::2])
print(arr[:2,::2])
print(arr[::-1,::-1])




[[20 30]
 [50 60]]
[[10 30]
 [70 90]]
[[10 30]
 [40 60]]
[[90 80 70]
 [60 50 40]
 [30 20 10]]


In [24]:
# Q7

arr = np.array([10,20,30,40,50])
print(arr[-2:])
print(arr[0:-1])
print(arr[::-1])

[40 50]
[10 20 30 40]
[50 40 30 20 10]


In [28]:
# Q8

arr = np.array([10,20,30,40,50])
print(arr[arr>25])
arr[arr>25]=0
print(arr)

[30 40 50]
[10 20  0  0  0]


In [40]:
#9

arr = np.array([
[10,20,30],
[40,50,60]
                 ])
print(arr + [1,2,3] )

[[11 22 33]
 [41 52 63]]


In [45]:
#10
arr = np.array([
[10,20,30],
[40,50,60]
                 ])
# arr = np.hstack((arr,[[1],[2]]))
arr = np.append(arr, [[1],[2]], axis=1)
print(arr)

[[10 20 30  1]
 [40 50 60  2]]


In [54]:
#11
arr = np.array([[1,2,3],
[4,5,6]])
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

21
[5 7 9]
[ 6 15]


In [57]:
#12
arr = np.array([[1,2,3],
[4,5,6]])
print(arr.mean(axis=1))
print(arr.max(axis=0))


[2. 5.]
[4 5 6]


In [58]:
#13
arr = np.array([
[1,2,3],
[4,5,6]
                ])

print(arr.reshape(2,3))
print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [60]:
#14
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.flatten())

[1 2 3 4 5 6]


In [71]:
#15
a = np.array([1,2,3])

b = a

b[0] = 100

print(a)

[100   2   3]


In [70]:
#16
a = np.array([1,2,3])

b = a.copy()

b[0] = 100
print(a)
print(b)


[1 2 3]
[100   2   3]


In [95]:
#17
arr = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
      ])
print(arr[1:2])
print(arr[:,1])
print((arr[::2,::2]))

[[4 5 6]]
[2 5 8]
[[1 3]
 [7 9]]


In [107]:
#18
arr=np.arange(1,4).reshape(3,1)
print(np.repeat(arr,3,axis=1))


[[1 1 1]
 [2 2 2]
 [3 3 3]]
